name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  guard:
    name: Validate tag and branch
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.on_master }}
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check
        name: Check tag is on master
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" != refs/tags/* ]] || [[ "${GITHUB_REF##refs/tags/}" != v* ]]; then
            echo "on_master=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git fetch origin master --depth=1
          COMMIT=$(git rev-parse "${GITHUB_SHA}^{commit}")
          if git merge-base --is-ancestor "$COMMIT" origin/master; then
            echo "on_master=true" >> "$GITHUB_OUTPUT"
          else
            echo "on_master=false" >> "$GITHUB_OUTPUT"
          fi

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/client
          # Remove previous build files
          clean: true
          # Remove history — avoiding exploding Git repository size
          single-commit: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
